### ISSUE TITLE
How to get the data?

### ISSUE THREAD

**Issue by shijianupc** [google/vulncode-db#105]
This is a very valuable project, thank you.
I want to investigate the files affected by the vulnerability, how can I get the data or the database dump?

**Comment by evonide** [comment]
Thanks I'm currently traveling but will reply to this request soon!
Generally, we can provide the newest dump. I'll either share it here or
directly via the site soon.

**Comment by evonide** [comment]
I've exported the full Cloud SQL instance ton [this file](https://storage.googleapis.com/vulncode-db.appspot.com/Cloud_SQL_Export_2021-12-05.sql.gz).
**Note:** I've replaced the user table though so you might need to update or add users in line 2864 of the unzipped .sql dump to avoid errors due to missing user accounts.

The data provided by the project, unless otherwise stated by https://github.com/google/vulncode-db/blob/master/README.md#third-party-data as the dump contains NVD/CVE data, is available under a CC-BY license.

**Comment by shijianupc** [comment]
Thank you very much!
